export default {
  products: [
    {
      _id:'1',
      name:'Akatsuki',
      image:'/images/product-1.jpg',
      size: '2x1',
      price: 100,
      creator: 'Goibo',
      creator_rating: 5.0,
      numReviews: 10,
      countInStock: 1,
    },
    {
      _id: '2',
      name: 'Washington Commanders',
      image: '/images/product-2.jpg',
      size: '2x1',
      price: 100,
      creator: 'Goibo',
      creator_rating: 5.0,
      numReviews: 10,
      countInStock: 1,
    },
    {
      _id: '3',
      name: 'Pink and Blue',
      image: '/images/product-3.jpg',
      size: '2x1',
      price: 100,
      creator: 'Goibo',
      creator_rating: 5.0,
      numReviews: 10,
      countInStock: 1,
    },
    {
      _id: '4',
      name: 'Sando San',
      image: '/images/product-4.jpg',
      size: '2x1',
      price: 100,
      creator: 'Goibo',
      creator_rating: 5.0,
      numReviews: 10,
      countInStock: 1,
    },
    {
      _id: '5',
      name: 'Gon x Killua',
      image: '/images/product-5.jpg',
      size: '2x1',
      price: 100,
      creator: 'Goibo',
      creator_rating: 5.0,
      numReviews: 10,
      countInStock: 1,
    },
  ]
}